### ISSUE TITLE
testPostEvent(com.intuit.wasabi.eventlog.impl.EventLogImplTest): failing intermittently

### ISSUE THREAD

**Issue by iizrailevsky** [intuit/wasabi#20]
testPostEvent(com.intuit.wasabi.eventlog.impl.EventLogImplTest)  Time elapsed: 0.623 sec  <<< FAILURE!
    Wanted but not invoked:
    eventLogListener.postEvent(
        com.intuit.wasabi.eventlog.events.SimpleEvent@2c95ac9e
    );
    -> at com.intuit.wasabi.eventlog.impl.EventLogImplTest.testPostEvent(EventLogImplTest.java:210)
    Actually, there were zero interactions with this mock.
    	at com.intuit.wasabi.eventlog.impl.EventLogImplTest.testPostEvent(EventLogImplTest.java:210)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
    	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:483)
    	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
    	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
    	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
    	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
    	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
    Running com.intuit.wasabi.eventlog.impl.NoopEventLogImplTest
    22:43:04.066 [Thread-11] INFO  c.i.w.eventlog.impl.EventLogImpl - Shutting down event system, posting remaining events -- incoming events are no longer accepted.
    Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 sec
    Running com.intuit.wasabi.eventlog.impl.EventLogEventEnvelopeTest
    Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
    Running com.intuit.wasabi.eventlog.EventLogServiceTest
    22:43:04.096 [main] INFO  c.i.wasabi.eventlog.EventLogService - already stopped EventLogService
    22:43:04.098 [main] INFO  c.i.wasabi.eventlog.EventLogSystem - Started EventLogThread with ID 37.
    22:43:04.098 [main] INFO  c.i.wasabi.eventlog.EventLogSystem - Interrupted EventLogThread with ID 37.
    22:43:04.098 [main] INFO  c.i.wasabi.eventlog.EventLogSystem - EventLogThread with ID 37 joined.
    22:43:04.099 [main] INFO  c.i.wasabi.eventlog.EventLogSystem - Started EventLogThread with ID 38.
    22:43:04.099 [main] INFO  c.i.wasabi.eventlog.EventLogService - already started EventLogService
    Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.026 sec
    Results :
    Failed tests:   testPostEvent(com.intuit.wasabi.eventlog.impl.EventLogImplTest): (..)

**Comment by Faedrivin** [comment]
The problem is here I assume:

    eventLog.postEvent(simpleEvent);
    // wait for the thread to actually post it
    Thread.sleep(600);

Maybe adjusting the [sleep timeout](https://github.com/intuit/wasabi/blob/206656bf44fd01af133f5335aa3b223339a4a5a5/modules/eventlog/src/test/java/com/intuit/wasabi/eventlog/impl/EventLogImplTest.java#L209) will fix this. The `EventLogImpl`'s main loop just polls for events every 500 ms while this expects it to be done after 600ms, if the two `Thread.sleep`s have some bad timings here (one taking a little longer during wait and the other rushing a bit) or some calls in the `eventDeque` take a few microseconds too long it might cause this problem.

There are a few more timeouts like this throughout the EventLog tests, I could move them to a constant or to a configuration variable. Alternatively we could reduce the [sleep timeout](https://github.com/intuit/wasabi/blob/206656bf44fd01af133f5335aa3b223339a4a5a5/modules/eventlog/src/main/java/com/intuit/wasabi/eventlog/impl/EventLogImpl.java#L162) of the EventLog.

**Comment by shoeffner** [comment]
resolved in #61
