### ISSUE TITLE
Can't start on MacOS

### ISSUE THREAD

**Issue by llambda** [intuit/wasabi#265]
I did:

```
gco 1.0.20170717233424
```

followed by:

```
 bin/wasabi.sh start   
```

and am seeing:

```
Successfully built 9f3c7da36c97
wasabi: starting
4a14bc2da8b4ba73f61de270613b3c5100f29bad08cfb72897909228d7059a1d
chill'ax error: not started

usage: container.sh [options] [commands]

options:
  -v | --verify [ true | false ]         : verify installation configuration; default: false
  -m | --migration [ true | false ]      : refresh cassandra migration scripts; default: false
  -s | --sleep [ sleep-time ]            : sleep/wait time in seconds; default: 3
  -h | --help                            : help message

commands:
  start[:wasabi,cassandra,mysql,docker]  : start all, wasabi, cassandra, mysql, docker
  stop[:wasabi,cassandra,mysql,docker]   : stop all, wasabi, cassandra, mysql, docker
  console[:cassandra,mysql]              : console all, cassandra, mysql
  status                                 : status
  remove[:wasabi,cassandra,mysql]]       : remove all, wasabi, cassandra, mysql



```

**Comment by brendanjryan** [comment]
@llambda is this all of the output? can you try starting each service individually? I'm betting that the mysql container is having issues coming up

**Comment by symadept** [comment]
I'm having the same issue. 
Successfully tagged wasabi-main:mshai4-1525274647
Successfully tagged wasabi-main:latest
wasabi: starting
27b24b6714d55fef3f213a9ce275f8cafbed0f2116bd6d68dc7cc25554460793
chill'ax error: not started

usage: container.sh [options] [commands]

**Comment by j33wang** [comment]
Having the same issue, anyone have more details on a workaround or how to go about debugging this?

It seems 'wasabi.sh status' is printing this out ("start:wasabi" calls "status") .

In 'wasabi.sh status', "wget -q --spider --tries=20 --waitretry=3 http://localhost:8080/api/v1/ping" isn't working.  

I'm seeing:
`
$ wget --spider http://localhost:8080/api/v1/ping
`
`
Spider mode enabled. Check if remote file exists.
--2018-05-08 19:39:52--  http://localhost:8080/api/v1/ping
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.
`

**Comment by brendanjryan** [comment]
👋 i'm not a maintainer but I can lend a hand if you are having issues. 

Can you attach the logs from the docker containers (`wasabi`, `mysql`, `cassandra`)? Most problems I have encountered starting up on mac can be traced back to one of those underlying systems.

**Comment by stefanrmeier** [comment]
Thanks @brendanjryan . I added the log files to the comment above. It seems that there is a problem with the injector.

**Comment by j33wang** [comment]
My docker logs for the wasabi container looks the same, where the root issue is:

"Caused by: com.datastax.driver.core.exceptions.InvalidQueryException: Unknown identifier source_url"

I've found this to be broken by this commit - https://github.com/intuit/wasabi/commit/afbfd8fdb1f5072907c37b68a00e80bc55a19335  from 13 days ago.  I reverted my local setup back to its parent commit - https://github.com/intuit/wasabi/commit/1d2f066541b176ee84c00dc9516b370553b76a40 - rebuilt, and restarted and that resolved the issue for me.

**Comment by symadept** [comment]
This is my error:

[*INFO*] *--- *maven-surefire-plugin:2.11:test *(default-test)* @
wasabi-experiment-objects* ---*

[*INFO*] Surefire report directory:
/Volumes/HDD/Projects/Wasabi/wasabi/modules/experiment-objects/target/surefire-reports

[*INFO*] Using configured provider
org.apache.maven.surefire.junitcore.JUnitCoreProvider


-------------------------------------------------------

 T E S T S

-------------------------------------------------------

Exception in thread "main" java.lang.reflect.InvocationTargetException

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native
Method)

at
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

at
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.base/java.lang.reflect.Method.invoke(Method.java:564)

at
java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:510)

at
java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:522)

Caused by: java.lang.RuntimeException: Class java/util/UUID could not be
instrumented.

at
org.jacoco.agent.rt.internal_8ff85ea.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:140)

at
org.jacoco.agent.rt.internal_8ff85ea.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:101)

at
org.jacoco.agent.rt.internal_8ff85ea.PreMain.createRuntime(PreMain.java:55)


at org.jacoco.agent.rt.internal_8ff85ea.PreMain.premain(PreMain.java:47)

Results :


... 6 more

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0


Caused by: java.lang.NoSuchFieldException: $jacocoAccess

at java.base/java.lang.Class.getField(Class.java:1958)

at
org.jacoco.agent.rt.internal_8ff85ea.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:138)

... 9 more

FATAL ERROR in native method: processing of -javaagent failed

[*INFO*]

/bin/sh: line 1: 14354 Abort trap: 6
/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/bin/java
'-javaagent:/Users/mshai4/.m2/repository/org/jacoco/org.jacoco.agent/0.7.9/org.jacoco.agent-0.7.9-runtime.jar=destfile=/Volumes/HDD/Projects/Wasabi/wasabi/modules/experiment-objects/../target/jacoco.exec,append=true,excludes=com/intuit/wasabi/tests/**/*.class'
-jar
/Volumes/HDD/Projects/Wasabi/wasabi/modules/experiment-objects/target/surefire/surefirebooter1553630742891458696.jar
/Volumes/HDD/Projects/Wasabi/wasabi/modules/experiment-objects/target/surefire/surefire15263645749158983248tmp
/Volumes/HDD/Projects/Wasabi/wasabi/modules/experiment-objects/target/surefire/surefire7617235667786685019tmp

[*INFO*]
*------------------------------------------------------------------------*

[*INFO*] *Skipping wasabi*

[*INFO*] This project has been banned from the build due to previous
failures.

[*INFO*]
*------------------------------------------------------------------------*

[*INFO*]
*------------------------------------------------------------------------*

[*INFO*] *Reactor Summary:*

[*INFO*]

[*INFO*] wasabi 1.0.20180427082617-SNAPSHOT .................
*SUCCESS* [  5.121
s]

[*INFO*] wasabi-experiment-objects ..........................
*FAILURE* [  3.898
s]

[*INFO*] wasabi-export ...................................... *SKIPPED*

[*INFO*] wasabi-assignment-objects .......................... *SKIPPED*

[*INFO*] wasabi-exceptions .................................. *SKIPPED*

[*INFO*] wasabi-analytics-objects ........................... *SKIPPED*

[*INFO*] wasabi-authentication-objects ...................... *SKIPPED*

[*INFO*] wasabi-eventlog .................................... *SKIPPED*

[*INFO*] wasabi-cassandra-datastax .......................... *SKIPPED*

[*INFO*] wasabi-authorization-objects ....................... *SKIPPED*

[*INFO*] wasabi-user-directory .............................. *SKIPPED*

[*INFO*] wasabi-feedback-objects ............................ *SKIPPED*

[*INFO*] wasabi-auditlog-objects ............................ *SKIPPED*

[*INFO*] wasabi-database .................................... *SKIPPED*

[*INFO*] wasabi-repository-datastax ......................... *SKIPPED*

[*INFO*] wasabi-experiment .................................. *SKIPPED*

[*INFO*] wasabi-assignment .................................. *SKIPPED*

[*INFO*] wasabi-util ........................................ *SKIPPED*

[*INFO*] wasabi-analytics ................................... *SKIPPED*

[*INFO*] wasabi-auditlog .................................... *SKIPPED*

[*INFO*] wasabi-event-objects ............................... *SKIPPED*

[*INFO*] wasabi-event ....................................... *SKIPPED*

[*INFO*] wasabi-email ....................................... *SKIPPED*

[*INFO*] wasabi-feedback .................................... *SKIPPED*

[*INFO*] wasabi-authentication .............................. *SKIPPED*

[*INFO*] wasabi-authorization ............................... *SKIPPED*

[*INFO*] wasabi-api ......................................... *SKIPPED*

[*INFO*] wasabi-functional-test ............................. *SKIPPED*

[*INFO*] wasabi-main ........................................ *SKIPPED*

[*INFO*] wasabi-swagger-ui 1.0.20180427082617-SNAPSHOT ...... *SKIPPED*

[*INFO*]
*------------------------------------------------------------------------*

[*INFO*] *BUILD FAILURE*

[*INFO*]
*------------------------------------------------------------------------*

[*INFO*] Total time: 11.561 s

[*INFO*] Finished at: 2018-05-09T16:37:11-05:00

[*INFO*]
*------------------------------------------------------------------------*

[*ERROR*] Failed to execute goal
org.apache.maven.plugins:maven-surefire-plugin:2.11:test *(default-test)*
on project wasabi-experiment-objects: *Error occured in starting fork,
check output in log* -> *[Help 1]*

[*ERROR*]

[*ERROR*] To see the full stack trace of the errors, re-run Maven with the
*-e* switch.

[*ERROR*] Re-run Maven using the *-X* switch to enable full debug logging.

[*ERROR*]

[*ERROR*] For more information about the errors and possible solutions,
please read the following articles:

[*ERROR*] *[Help 1]*
http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

[*ERROR*]

[*ERROR*] After correcting the problems, you can resume the build with the
command

[*ERROR*]   *mvn <goals> -rf :wasabi-experiment-objects*

error: invalid: mvn  -Pdevelopment clean
org.jacoco:jacoco-maven-plugin:prepare-agent findbugs:check test package
javadoc:aggregate


usage: build.sh [options]


options:

  -b | --build [ true | false ]  : build; default: false

  -p | --profile [profile]       : build profile; default: development

  -t | --test [ true | false ]   : test; default: false

  -h | --help                    : help message

wasabi: [Start] creating keyspace and migration schemas

cqlsh  --cqlversion="3.2.1"  -e "CREATE KEYSPACE IF NOT EXISTS
wasabi_experiments WITH replication = {'class' : 'SimpleStrategy',
'replication_factor' : 1};" --username= --password="" wasabi-cassandra 9042

java -jar -Dcassandra.migration.keyspace.name=wasabi_experiments
-Dcassandra.migration.cluster.port=9042
    -Dcassandra.migration.cluster.username=
-Dcassandra.migration.cluster.password=
    -Dcassandra.migration.scripts.locations=filesystem:/wasabi/mutation
   -Dcassandra.migration.cluster.contactpoints=wasabi-cassandra
    /wasabi/cassandra-migration.jar migrate

Cassandra Migration 0.9

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".

SLF4J: Defaulting to no-operation (NOP) logger implementation

SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further
details.

Connected to cluster: Test Cluster

Data center: datacenter1; Host: wasabi-cassandra/172.18.0.2

Current version of keyspace wasabi_experiments: 036

Keyspace wasabi_experiments is up to date, no migration necessary

wasabi: [DONE] creating keyspace and migration schemas

Warning: Using a password on the command line interface can be insecure.

wasabi: building

Sending build context to Docker daemon  53.21MB

Step 1/22 : from centos

 ---> e934aafc2206

Step 2/22 : ENV WASABI_MODULE wasabi-main

 ---> Using cache

 ---> 0bf7579d09f2

Step 3/22 : ENV WASABI_UI_MODULE wasabi-ui-main

 ---> Using cache

 ---> dd2719161f17

Step 4/22 : ENV WASABI_PORT 8080

 ---> Using cache

 ---> 2573d1e30ef9

Step 5/22 : ENV WASABI_JMX_PORT 8090

 ---> Using cache

 ---> a2ed7423cf28

Step 6/22 : ENV WASABI_DEBUG_PORT 8180

 ---> Using cache

 ---> a68e196becf5

Step 7/22 : ENV WASABI_SRC_DIR
wasabi-main-1.0.20180427082617-SNAPSHOT-development

 ---> Using cache

 ---> 18963b9e983c

Step 8/22 : ENV WASABI_HOME
/usr/local/wasabi-main-1.0.20180427082617-SNAPSHOT-development

 ---> Using cache

 ---> ff93c37f061f

Step 9/22 : ENV WASABI_JAVA_OPTIONS ""

 ---> Using cache

 ---> 2952879b819a

Step 10/22 : ENV JDK_MAJOR_VERSION 8u131

 ---> Using cache

 ---> b784ad9d6406

Step 11/22 : ENV JDK_MINOR_VERSION b11

 ---> Using cache

 ---> df54236263fc

Step 12/22 : ENV JDK_VERSION ${JDK_MAJOR_VERSION}-${JDK_MINOR_VERSION}

 ---> Using cache

 ---> 81fb68a173e4

Step 13/22 : RUN yum -y update && yum install -y wget

 ---> Using cache

 ---> ded0b885289f

Step 14/22 : RUN wget --no-check-certificate --no-cookies --header "Cookie:
oraclelicense=accept-securebackup-cookie"
http://download.oracle.com/otn-pub/java/jdk/${JDK_VERSION}/d54c1d3a095b4ff2b6607d096fa80163/jdk-${JDK_MAJOR_VERSION}-linux-x64.rpm
&&
rpm -ivh jdk-${JDK_MAJOR_VERSION}-linux-x64.rpm && rm
jdk-${JDK_MAJOR_VERSION}-linux-x64.rpm

 ---> Using cache

 ---> 3fdf79244108

Step 15/22 : COPY ./ ${WASABI_HOME}/

 ---> Using cache

 ---> a26e0a029650

Step 16/22 : COPY entrypoint.sh /usr/local/bin/

 ---> Using cache

 ---> dc1710f80954

Step 17/22 : RUN sed -i -e $'s/1>>.*2>&1//' ${WASABI_HOME}/bin/run
2>/dev/null;

 ---> Using cache

 ---> 94cd96e6f941

Step 18/22 : EXPOSE ${WASABI_PORT}

 ---> Using cache

 ---> cf58122b2a76

Step 19/22 : EXPOSE ${WASABI_JMX_PORT}

 ---> Using cache

 ---> 244169908972

Step 20/22 : EXPOSE ${WASABI_DEBUG_PORT}

 ---> Using cache

 ---> 2cfb021bb4aa

Step 21/22 : ENTRYPOINT ["entrypoint.sh"]

 ---> Using cache

 ---> 663209f3c3f0

Step 22/22 : CMD ["wasabi"]

 ---> Using cache

 ---> 1d2df2465eb0

Successfully built 1d2df2465eb0

Successfully tagged wasabi-main:mshai4-1525901846

Successfully tagged wasabi-main:latest

wasabi: starting

595b58482e889a8f41c0d40f3673792b3d0b6c8b21294b7c84cf669596984faa

chill'ax error: not started


usage: container.sh [options] [commands]


options:

  -v | --verify [ true | false ]         : verify installation
configuration; default: false

  -m | --migration [ true | false ]      : refresh cassandra migration
scripts; default: false

  -s | --sleep [ sleep-time ]            : sleep/wait time in seconds;
default: 3

  -h | --help                            : help message


commands:

  start[:wasabi,cassandra,mysql,docker]  : start all, wasabi, cassandra,
mysql, docker

  stop[:wasabi,cassandra,mysql,docker]   : stop all, wasabi, cassandra,
mysql, docker

  console[:cassandra,mysql]              : console all, cassandra, mysql

  status                                 : status

  remove[:wasabi,cassandra,mysql]]       : remove all, wasabi, cassandra,
mysql

Any thing I can do better here?

**Comment by j33wang** [comment]
fwiw - My workaround was done on an Ubuntu box (it doesn't build on my Mac for some reason, haven't had a chance to look into why yet).

@symadept the exceptions you're seeing from the test cases shouldn't matter.  Looking towards the tail end of your output, it looks like your docker containers are up; and you can verify by running "docker ps" which should print out something like below:


:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                     NAMES
06d7988219cb        wasabi-main         "entrypoint.sh wasabi"   23 hours ago        Up 23 hours         0.0.0.0:8080->8080/tcp, 0.0.0.0:8090->8090/tcp, 0.0.0.0:8180->8180/tcp    wasabi-main
64acc3782bda        mysql:5.6           "docker-entrypoint..."   2 days ago          Up 24 hours         0.0.0.0:3306->3306/tcp                                                    wasabi-mysql
ea50488a93fd        cassandra:2.1       "docker-entrypoint..."   2 days ago          Up 24 hours         7000-7001/tcp, 0.0.0.0:9042->9042/tcp, 7199/tcp, 0.0.0.0:9160->9160/tcp   wasabi-cassandra

Check the docker logs in your wasabi container by doing "docker logs -f <container_id>"  (docker ps will give you your container id) and share any errors/exceptions you see in those logs

**Comment by stefanrmeier** [comment]
@j33wang Thanks! I can confirm your analysis and the workaround. After rebuilding based on 1d2f066 it works.

**Comment by benalman-toast** [comment]
I had the same problem on Ubuntu 16.04 (x64) in Virtualbox, and checking out `1d2f066` allowed me to get it to start. It would be nice if we didn't have to workaround this error in this way.

**Comment by yinyuxuan2016** [comment]
---> 974cb2c7c819
Successfully built 974cb2c7c819
Successfully tagged wasabi-main:dongbiaozheng-1530076181
Successfully tagged wasabi-main:latest
wasabi: starting
i had the same problem on MAC,
chill'ax error: not started

usage: container.sh [options] [commands]

options:
  -v | --verify [ true | false ]         : verify installation configuration; default: false
  -m | --migration [ true | false ]      : refresh cassandra migration scripts; default: false
  -s | --sleep [ sleep-time ]            : sleep/wait time in seconds; default: 3
  -h | --help                            : help message

commands:
  start[:wasabi,cassandra,mysql,docker]  : start all, wasabi, cassandra, mysql, docker
  stop[:wasabi,cassandra,mysql,docker]   : stop all, wasabi, cassandra, mysql, docker
  console[:cassandra,mysql]              : console all, cassandra, mysql
  status                                 : status
  remove[:wasabi,cassandra,mysql]]       : remove all, wasabi, cassandra, mysql

**Comment by jillmoto** [comment]
Still getting the same issue on Mac OS 10.11 today.
Reverting to [1d2f066](https://github.com/intuit/wasabi/commit/1d2f066541b176ee84c00dc9516b370553b76a40) also worked for me. Thanks @j33wang

**Comment by shaikhimran786** [comment]
Mac OS High Sierra, version 10.13.4, Reverting to 1d2f066 also worked for me too, Thanks @j33wang.

**Comment by kstromeiraos** [comment]
Thanks @j33wang , reverting to 1d2f066 worked for me too! This has been around for a while, would be nice to have a fix for it...

**Comment by chirag-nirmal-ck** [comment]
reverting to 1d2f066, rebuilding  and starting did not work for me on mac os 10.13.6

**Comment by chiragnirmal** [comment]
I am still getting `chill'ax error: not started` even after reverting to `1d2f066` on mac os 10.13.6 (17G65).
