### ISSUE TITLE
Schema `wasabi` contains a failed migration to version 006

### ISSUE THREAD

**Issue by kstromeiraos** [intuit/wasabi#348]
Hi all,

Experiencing these errors trying to deploy Wasabi with remote Cassandra/RDS.

```
34) Error injecting constructor, com.googlecode.flyway.core.api.FlywayException: Schema `wasabi` contains a failed migration to version 006 !
  at com.intuit.wasabi.repository.database.DatabaseFavoritesRepository.<init>(DatabaseFavoritesRepository.java:47)
  while locating com.intuit.wasabi.repository.database.DatabaseFavoritesRepository
  at com.intuit.wasabi.repository.database.DatabaseExperimentRepositoryModule.configure(DatabaseExperimentRepositoryModule.java:43) (via modules: com.intuit.wasabi.api.ApiModule -> com.intuit.wasabi.repository.database.DatabaseExperimentRepositoryModule)
  while locating com.intuit.wasabi.repository.FavoritesRepository
    for parameter 0 at com.intuit.wasabi.experiment.impl.FavoritesImpl.<init>(FavoritesImpl.java:39)
  while locating com.intuit.wasabi.experiment.impl.FavoritesImpl
  at com.intuit.wasabi.experiment.ExperimentsModule.configure(ExperimentsModule.java:52) (via modules: com.intuit.wasabi.api.ApiModule -> com.intuit.wasabi.analytics.AnalyticsModule -> com.intuit.wasabi.experiment.ExperimentsModule)
  while locating com.intuit.wasabi.experiment.Favorites
Caused by: com.googlecode.flyway.core.api.FlywayException: Schema `wasabi` contains a failed migration to version 006 !
	at com.googlecode.flyway.core.command.DbMigrate$1.doInTransaction(DbMigrate.java:175)
	at com.googlecode.flyway.core.command.DbMigrate$1.doInTransaction(DbMigrate.java:135)
	at com.googlecode.flyway.core.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at com.googlecode.flyway.core.command.DbMigrate.migrate(DbMigrate.java:135)
...
```

**OS: Ubuntu 16.04**

**Steps to reproduce**

1. Bootstrap Wasabi
```
git clone https://github.com/intuit/wasabi && cd wasabi
./bin/wasabi.sh bootstrap
sudo reboot
```

2. Add this to `pom.xml`

```
  <mysql.host>prod-mysql-wasabi.<whatever>.amazonaws.com</mysql.host>
  <mysql.port>3306</mysql.port>
  <mysql.dbName>wasabi</mysql.dbName>
  <mysql.username>wasabi</mysql.username>
  <mysql.password>'sensitive'</mysql.password>
  <mysql.numPartitions>1</mysql.numPartitions>
  <mysql.minConnections>10</mysql.minConnections>
  <mysql.maxConnections>30</mysql.maxConnections>
  <mysql.Args>verifyServerCertificate=false&amp;useSSL=false&amp;requireSSL=false&amp;autoReconnect=true&amp;autoReconnectForPools=true</mysql.Args>

  <cassandra.username>cassandra</cassandra.username>
  <cassandra.password>'sensitive'</cassandra.password>
  <cassandra.experiments.keyspaceName>wasabi_experiments</cassandra.experiments.keyspaceName>
  <cassandra.experiments.nodeHosts>internal-prod-wasabi-<whatever>.us-east-1.elb.amazonaws.com</cassandra.experiments.nodeHosts>
  <cassandra.experiments.port>9042</cassandra.experiments.port>
  <cassandra.experiments.useSSL>false</cassandra.experiments.useSSL>
  <cassandra.local.dc>us-east</cassandra.local.dc>
  <cassandra.experiments.defaultReadConsistency>LOCAL_ONE</cassandra.experiments.defaultReadConsistency>
  <cassandra.experiments.defaultWriteConsistency>LOCAL_ONE</cassandra.experiments.defaultWriteConsistency>
  <cassandra.experiments.replicationFactor>1</cassandra.experiments.replicationFactor>
  <cassandra.events.nodeHosts>internal-prod-wasabi-<whatever>.us-east-1.elb.amazonaws.com</cassandra.events.nodeHosts>
  <cassandra.events.port>9042</cassandra.events.port>
```

3. Migrate data

```
# Download Cassandra migration tool
wget https://oss.sonatype.org/content/repositories/public/com/builtamont/cassandra-migration/0.9/cassandra-migration-0.9-jar-with-dependencies.jar
export CASSANDRA_MIGRATION=/home/ubuntu/wasabi/cassandra-migration-0.9-jar-with-dependencies.jar
export MIGRATION_SCRIPT=/home/ubuntu/wasabi/modules/repository-datastax/src/main/resources/com/intuit/wasabi/repository/impl/cassandra/migration

# Install Cassandra 2.1
echo "deb http://www.apache.org/dist/cassandra/debian 21x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
curl https://www.apache.org/dist/cassandra/KEYS | sudo apt-key add -
sudo apt-key adv --keyserver pool.sks-keyservers.net --recv-key A278B781FE4B2BDA
sudo apt-get update
sudo apt-get install cassandra
# Apply migrations
CQLSH_USERNAME=cassandra CQLSH_PASSWORD='sensitive' CQLSH_HOST=internal-prod-wasabi-<whatever>.us-east-1.elb.amazonaws.com bin/docker/migration.sh
```

4. Build and start wasabi

```
# Build application
MYSQL_HOST=prod-mysql-wasabi.<whatever>.amazonaws.com NODE_HOST=internal-prod-wasabi-<whatever>.us-east-1.elb.amazonaws.com ./bin/wasabi.sh -t false build

# Create docker network for Wasabi (start:wasabi throws an error if this is not done)
docker network create wasabi_nw

# Start wasabi app container
MYSQL_HOST=prod-mysql-wasabi.<whatever>.amazonaws.com NODE_HOST=internal-prod-wasabi-<whatever>.us-east-1.elb.amazonaws.com ./bin/wasabi.sh -t false start:wasabi
```

Thanks in advance!

**Comment by kstromeiraos** [comment]
I managed to "solve" this with this workaround.

- Build and start Wasabi on Docker containers (it should work)
```
./bin/wasabi.sh build
./bin/wasabi.sh start
```

- Dump/restore Wasabi MySQL Docker container data
```
docker exec -it wasabi-mysql bash
# Default password is readwrite
mysqldump -u readwrite -p --databases wasabi > wasabi_mysql_dump.sql
exit

docker cp wasabi-mysql:/wasabi_mysql_dump.sql $(pwd)

vi wasabi_dump_db.sql # Replace lines containing definer=readwrite for definer=wasabi

mysql -u wasabi -p --host=<your_remote_host> wasabi_mysql_dump.sql
```

After that, do the steps posted on the first post.

**Comment by patchoak-abacus** [comment]
Had the same issue migrating to a remote database too. Turns out it occurs when MySQL has binary logging turned on. Custom defined functions and triggers couldn't be declared unless the flag 'log_bin_trust_creators = 1' is set.
